name: build

on: 
  push:
    paths:
      - '.github/workflows/build.yml'
      - '.swiftlint.yml'
      - '**/*.swift'
    tags-ignore:
      - '**'
  pull_request:
    paths:
      - '.github/workflows/build.yml'
      - '.swiftlint.yml'
      - '**/*.swift'
    tags-ignore:
      - '**'

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache build
        uses: actions/cache@v3
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      - name: Run tests
        run: make test
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Lint
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --strict
