name: build

on: 
  push:
    paths:
      - '.github/workflows/build.yml'
      - '.swiftlint.yml'
      - '**/*.swift'
  pull_request:
    paths:
      - '.github/workflows/build.yml'
      - '.swiftlint.yml'
      - '**/*.swift'
      
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: make test
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Lint
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --strict
